# Generated by Django 5.2.4 on 2025-10-10 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('MEDICATION', 'Medicamento'), ('PRODUCT', 'Produto')], default='PRODUCT', max_length=16, verbose_name='Tipo')),
                ('name', models.CharField(max_length=160, verbose_name='Nome')),
                ('scientific_name', models.CharField(blank=True, max_length=160, verbose_name='Nome clínico/laboratorial')),
                ('sku', models.CharField(blank=True, max_length=64, verbose_name='Código/SKU')),
                ('unit', models.CharField(default='un', max_length=16, verbose_name='Unidade')),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço')),
                ('track_inventory', models.BooleanField(default=True, verbose_name='Controla estoque')),
                ('quantity_on_hand', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Qtd em estoque')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160, verbose_name='Serviço')),
                ('description', models.TextField(blank=True, verbose_name='Descrição')),
                ('base_price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço base')),
                ('duration_minutes', models.PositiveIntegerField(default=30, verbose_name='Duração (min)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Serviço',
                'verbose_name_plural': 'Serviços',
            },
        ),
        migrations.CreateModel(
            name='ServiceMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_required', models.DecimalField(decimal_places=3, default=1, max_digits=12, verbose_name='Qtd por serviço')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_usages', to='inventory.product')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='inventory.service')),
            ],
            options={
                'verbose_name': 'Material de Serviço',
                'verbose_name_plural': 'Materiais de Serviço',
            },
        ),
        migrations.CreateModel(
            name='StockMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('move_type', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Saída'), ('ADJUST', 'Ajuste')], max_length=8, verbose_name='Tipo')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Quantidade')),
                ('unit_cost', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo unitário')),
                ('reason', models.CharField(blank=True, max_length=32, verbose_name='Motivo')),
                ('reference', models.CharField(blank=True, max_length=64, verbose_name='Referência')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Observações')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moves', to='inventory.product')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_moves', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Movimento de Estoque',
                'verbose_name_plural': 'Movimentos de Estoque',
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='Nome')),
                ('cnpj_cpf', models.CharField(blank=True, max_length=20, verbose_name='CNPJ/CPF')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('phone', models.CharField(blank=True, max_length=32, verbose_name='Telefone')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Endereço')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Cidade')),
                ('state', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suppliers', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Fornecedor',
                'verbose_name_plural': 'Fornecedores',
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='inventory.supplier'),
        ),
        migrations.AddIndex(
            model_name='service',
            index=models.Index(fields=['professional', 'is_active', 'name'], name='inventory_s_profess_84a718_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('professional', 'name')},
        ),
        migrations.AddIndex(
            model_name='servicematerial',
            index=models.Index(fields=['service', 'product'], name='inventory_s_service_1f22aa_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicematerial',
            unique_together={('service', 'product')},
        ),
        migrations.AddIndex(
            model_name='stockmove',
            index=models.Index(fields=['professional', 'product', 'move_type', 'created_at'], name='inventory_s_profess_4538a2_idx'),
        ),
        migrations.AddIndex(
            model_name='supplier',
            index=models.Index(fields=['professional', 'name'], name='inventory_s_profess_04fecf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='supplier',
            unique_together={('professional', 'name')},
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['professional', 'type', 'name'], name='inventory_p_profess_e35339_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['professional', 'is_active'], name='inventory_p_profess_66401a_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('professional', 'name')},
        ),
    ]
