# docker-compose.local.yml
version: "3.9"
services:
  db:
    image: postgres:16-alpine
    container_name: clinic-local-db
    environment:
      POSTGRES_DB: clinic_local
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinicpass
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "clinic"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
