# docker-compose.local.yml
services:
  db:
    image: postgres:16-alpine
    container_name: clinic-local-db
    environment:
      POSTGRES_DB: clinic_local
      POSTGRES_USER: clinic
      POSTGRES_PASSWORD: clinicpass
      POSTGRES_HOST_AUTH_METHOD: trust # dev-only: allow host connections without password
      POSTGRES_INITDB_ARGS: "--encoding=UTF8"
    ports:
      - "55432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./scripts/docker-init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "clinic", "-d", "clinic_local"]
      interval: 5s
      timeout: 5s
      retries: 10
volumes:
  db_data:
