# Generated by Django 5.2.4 on 2025-09-01 17:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('register', '0029_devicesession'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80, verbose_name='Título')),
                ('visit_type', models.CharField(choices=[('avaliacao', 'Avaliação'), ('retorno', 'Retorno'), ('procedimento', 'Procedimento'), ('outro', 'Outro')], default='avaliacao', max_length=20, verbose_name='Tipo de consulta')),
                ('start_at', models.DateTimeField(verbose_name='Início')),
                ('end_at', models.DateTimeField(verbose_name='Fim')),
                ('location', models.CharField(blank=True, max_length=120, verbose_name='Local')),
                ('notes', models.TextField(blank=True, verbose_name='Observações')),
                ('status', models.CharField(choices=[('scheduled', 'Agendado'), ('done', 'Realizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=12, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='register.client', verbose_name='Cliente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'ordering': ['start_at'],
                'indexes': [models.Index(fields=['professional', 'start_at'], name='agenda_appo_profess_414a4b_idx'), models.Index(fields=['client', 'start_at'], name='agenda_appo_client__16d7f2_idx'), models.Index(fields=['status'], name='agenda_appo_status_8e291c_idx')],
            },
        ),
    ]
