# Generated by Django 5.2.4 on 2025-09-14 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='visit_type',
            field=models.CharField(choices=[('avaliacao', 'Avaliação'), ('retorno', 'Retorno'), ('procedimento', 'Procedimento'), ('outro', 'Outro'), ('consulta', 'Consulta')], default='consulta', max_length=20, verbose_name='Tipo de consulta'),
        ),
    ]
