# Generated by Django 5.2.4 on 2025-09-28 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0003_device_audit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='finalizeaudit',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='agenda_appo_created_97330c_idx',
            old_name='agenda_app_created__idx',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='agenda_appo_ended_d_39c375_idx',
            old_name='agenda_app_ended_dev_idx',
        ),
        migrations.RenameIndex(
            model_name='finalizeaudit',
            new_name='agenda_fina_appoint_ce4e3c_idx',
            old_name='agenda_fin_appointm_idx',
        ),
        migrations.RenameIndex(
            model_name='finalizeaudit',
            new_name='agenda_fina_profess_4c256e_idx',
            old_name='agenda_fin_professi_idx',
        ),
        migrations.RenameIndex(
            model_name='finalizeaudit',
            new_name='agenda_fina_client__07a691_idx',
            old_name='agenda_fin_client_c_idx',
        ),
        migrations.RenameIndex(
            model_name='finalizeaudit',
            new_name='agenda_fina_device__ee4423_idx',
            old_name='agenda_fin_device_i_idx',
        ),
    ]
