# Generated by Django 5.2.4 on 2025-10-09 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0005_finalized_canceled_timestamps'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='appointment',
            new_name='agenda_appo_finaliz_86159e_idx',
            old_name='agenda_appo_finaliz_fts',
        ),
        migrations.RenameIndex(
            model_name='appointment',
            new_name='agenda_appo_cancele_efbfc3_idx',
            old_name='agenda_appo_cancelo_fts',
        ),
    ]
