# Generated by Django 5.2.4 on 2026-04-07 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0010_appointment_whatsapp_confirmed'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='charge',
            new_name='agenda_char_profess_b69a39_idx',
            old_name='agenda_charg_profess_a9145c_idx',
        ),
        migrations.RenameIndex(
            model_name='charge',
            new_name='agenda_char_appoint_e94b92_idx',
            old_name='agenda_charg_appoint_0ce768_idx',
        ),
        migrations.RenameIndex(
            model_name='charge',
            new_name='agenda_char_encount_083045_idx',
            old_name='agenda_charg_encount_2bd985_idx',
        ),
        migrations.RenameIndex(
            model_name='charge',
            new_name='agenda_char_created_70c961_idx',
            old_name='agenda_charg_created_30313b_idx',
        ),
        migrations.RenameIndex(
            model_name='chargeitem',
            new_name='agenda_char_charge__44751c_idx',
            old_name='agenda_charg_charge__22e18d_idx',
        ),
        migrations.RenameIndex(
            model_name='chargeitem',
            new_name='agenda_char_item_ty_7eff13_idx',
            old_name='agenda_charg_item_ty_4fa031_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalrecord',
            new_name='agenda_clin_profess_6aac04_idx',
            old_name='agenda_clini_profess_98f937_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalrecord',
            new_name='agenda_clin_client__1ef601_idx',
            old_name='agenda_clini_client__1c85c0_idx',
        ),
        migrations.RenameIndex(
            model_name='clinicalrecord',
            new_name='agenda_clin_encount_37f357_idx',
            old_name='agenda_clini_encount_2680f7_idx',
        ),
        migrations.RenameIndex(
            model_name='encounter',
            new_name='agenda_enco_profess_97b55b_idx',
            old_name='agenda_encou_profess_5074bf_idx',
        ),
        migrations.RenameIndex(
            model_name='encounter',
            new_name='agenda_enco_profess_96f959_idx',
            old_name='agenda_encou_profess_114294_idx',
        ),
        migrations.RenameIndex(
            model_name='encounter',
            new_name='agenda_enco_client__0b89ac_idx',
            old_name='agenda_encou_client__07ddf0_idx',
        ),
    ]
