# Generated by Django 5.2.4 on 2026-05-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agenda', '0013_appointment_pending_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Agendado'), ('ongoing', 'Em andamento'), ('pending', 'Pendente'), ('done', 'Realizado'), ('canceled', 'Cancelado')], default='scheduled', max_length=12, verbose_name='Status'),
        ),
    ]
