# Generated by Django 5.2.3 on 2025-06-29 15:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0002_alter_client_prof_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='prof_id',
            new_name='professional',
        ),
        migrations.AddField(
            model_name='client',
            name='address_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='client',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AddField(
            model_name='client',
            name='clinical_history',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico clínico'),
        ),
        migrations.AddField(
            model_name='client',
            name='dermatological_left',
            field=models.TextField(blank=True, null=True, verbose_name='Dermatológico esquerdo'),
        ),
        migrations.AddField(
            model_name='client',
            name='dermatological_right',
            field=models.TextField(blank=True, null=True, verbose_name='Dermatológico direito'),
        ),
        migrations.AddField(
            model_name='client',
            name='footwear_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outro calçado'),
        ),
        migrations.AddField(
            model_name='client',
            name='footwear_used',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Calçado usado'),
        ),
        migrations.AddField(
            model_name='client',
            name='had_surgery',
            field=models.BooleanField(blank=True, null=True, verbose_name='Já fez cirurgia'),
        ),
        migrations.AddField(
            model_name='client',
            name='is_pregnant',
            field=models.BooleanField(blank=True, null=True, verbose_name='Está grávida'),
        ),
        migrations.AddField(
            model_name='client',
            name='medication_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da medicação'),
        ),
        migrations.AddField(
            model_name='client',
            name='pain_sensitivity',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sensibilidade à dor'),
        ),
        migrations.AddField(
            model_name='client',
            name='perfusion_left',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Perfusão pé esquerdo'),
        ),
        migrations.AddField(
            model_name='client',
            name='perfusion_left_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outra perfusão esquerda'),
        ),
        migrations.AddField(
            model_name='client',
            name='perfusion_right',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Perfusão pé direito'),
        ),
        migrations.AddField(
            model_name='client',
            name='perfusion_right_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outra perfusão direita'),
        ),
        migrations.AddField(
            model_name='client',
            name='plantar_view_left',
            field=models.TextField(blank=True, null=True, verbose_name='Vista plantar esquerda'),
        ),
        migrations.AddField(
            model_name='client',
            name='plantar_view_left_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outra vista plantar esquerda'),
        ),
        migrations.AddField(
            model_name='client',
            name='plantar_view_right',
            field=models.TextField(blank=True, null=True, verbose_name='Vista plantar direita'),
        ),
        migrations.AddField(
            model_name='client',
            name='plantar_view_right_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outra vista plantar direita'),
        ),
        migrations.AddField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='client',
            name='pregnancy_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da gravidez'),
        ),
        migrations.AddField(
            model_name='client',
            name='professional_profile',
            field=models.TextField(blank=True, null=True, verbose_name='Procedimentos realizados'),
        ),
        migrations.AddField(
            model_name='client',
            name='professional_profile_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outros procedimentos'),
        ),
        migrations.AddField(
            model_name='client',
            name='sock_used',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Meia usada'),
        ),
        migrations.AddField(
            model_name='client',
            name='surgery_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da cirurgia'),
        ),
        migrations.AddField(
            model_name='client',
            name='takes_medication',
            field=models.BooleanField(blank=True, null=True, verbose_name='Toma medicação'),
        ),
        migrations.AddField(
            model_name='client',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AddField(
            model_name='professional',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Criado em'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Atualizado em'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Primeiro nome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='email',
            field=models.EmailField(max_length=254, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Especialidade'),
        ),
    ]
