# Generated by Django 5.2.3 on 2025-07-01 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0003_rename_prof_id_client_professional_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dermatological_left',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dermatological_right',
        ),
        migrations.RemoveField(
            model_name='client',
            name='professional_profile',
        ),
        migrations.RemoveField(
            model_name='client',
            name='professional_profile_other',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='crm',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='client',
            name='clinical_history_other',
            field=models.TextField(blank=True, verbose_name='Outro histórico'),
        ),
        migrations.AddField(
            model_name='client',
            name='dermatological_pathologies_left',
            field=models.TextField(blank=True, verbose_name='Patologias pé esquerdo'),
        ),
        migrations.AddField(
            model_name='client',
            name='dermatological_pathologies_right',
            field=models.TextField(blank=True, verbose_name='Patologias pé direito'),
        ),
        migrations.AddField(
            model_name='client',
            name='professional_procedures',
            field=models.TextField(blank=True, verbose_name='Procedimentos realizados'),
        ),
        migrations.AddField(
            model_name='professional',
            name='city',
            field=models.CharField(blank=True, max_length=50, verbose_name='Cidade'),
        ),
        migrations.AddField(
            model_name='professional',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Telefone'),
        ),
        migrations.AddField(
            model_name='professional',
            name='register_number',
            field=models.CharField(default='CRM123', max_length=30, unique=True, verbose_name='Registro Profissional'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='professional',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_number',
            field=models.CharField(blank=True, default='0', max_length=10, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='address_street',
            field=models.CharField(blank=True, default='0', max_length=255, verbose_name='Rua'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, default='Santos', max_length=100, verbose_name='Cidade'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='clinical_history',
            field=models.TextField(blank=True, default='0', verbose_name='Histórico clínico'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='mail@mail', max_length=254, unique=True, verbose_name='E-mail'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='footwear_other',
            field=models.TextField(blank=True, default='outros', verbose_name='Outro calçado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='footwear_used',
            field=models.CharField(blank=True, default='outros', max_length=50, verbose_name='Calçado usado'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='had_surgery',
            field=models.BooleanField(null=True, verbose_name='Já fez cirurgia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_pregnant',
            field=models.BooleanField(null=True, verbose_name='Está grávida'),
        ),
        migrations.AlterField(
            model_name='client',
            name='medication_details',
            field=models.TextField(blank=True, default='medicamento', verbose_name='Detalhes da medicação'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='pain_sensitivity',
            field=models.CharField(blank=True, default='2', max_length=50, verbose_name='Sensibilidade à dor'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='perfusion_left',
            field=models.CharField(blank=True, default='Calosidade', max_length=50, verbose_name='Perfusão pé esquerdo'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='perfusion_left_other',
            field=models.TextField(blank=True, default='sem', verbose_name='Outra perfusão esquerda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='perfusion_right',
            field=models.CharField(blank=True, default='sem', max_length=50, verbose_name='Perfusão pé direito'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='perfusion_right_other',
            field=models.TextField(blank=True, default='outro', verbose_name='Outra perfusão direita'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='plantar_view_left',
            field=models.TextField(blank=True, default='sem', verbose_name='Vista plantar esquerda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='plantar_view_left_other',
            field=models.TextField(blank=True, default='sem', verbose_name='Outra vista plantar esquerda'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='plantar_view_right',
            field=models.TextField(blank=True, default='sem', verbose_name='Vista plantar direita'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='plantar_view_right_other',
            field=models.TextField(blank=True, verbose_name='Outra vista plantar direita'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pregnancy_details',
            field=models.TextField(blank=True, verbose_name='Detalhes da gravidez'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sock_used',
            field=models.CharField(blank=True, max_length=50, verbose_name='Meia usada'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=2, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surgery_details',
            field=models.TextField(blank=True, verbose_name='Detalhes da cirurgia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='takes_medication',
            field=models.BooleanField(null=True, verbose_name='Toma medicação'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Ativo'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='last_name',
            field=models.CharField(max_length=70, verbose_name='Sobrenome'),
        ),
        migrations.AlterField(
            model_name='professional',
            name='specialty',
            field=models.CharField(blank=True, max_length=100, verbose_name='Especialidade'),
        ),
    ]
