# Generated by Django 5.2.3 on 2025-07-01 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0004_remove_client_dermatological_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
