# Generated by Django 5.2.4 on 2025-07-06 21:09

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0006_accesscode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region='BR', verbose_name='Telefone'),
        ),
    ]
