# Generated by Django 5.2.4 on 2025-07-08 19:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0007_alter_professional_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='address_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Número'),
        ),
        migrations.AlterField(
            model_name='client',
            name='address_street',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Rua'),
        ),
        migrations.AlterField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clinical_history',
            field=models.TextField(blank=True, null=True, verbose_name='Histórico clínico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='clinical_history_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outro histórico'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dermatological_pathologies_left',
            field=models.TextField(blank=True, null=True, verbose_name='Patologias pé esquerdo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='dermatological_pathologies_right',
            field=models.TextField(blank=True, null=True, verbose_name='Patologias pé direito'),
        ),
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='E-mail'),
        ),
        migrations.AlterField(
            model_name='client',
            name='footwear_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outro calçado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='footwear_used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Calçado usado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='had_surgery',
            field=models.BooleanField(blank=True, null=True, verbose_name='Já fez cirurgia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='is_pregnant',
            field=models.BooleanField(blank=True, null=True, verbose_name='Está grávida'),
        ),
        migrations.AlterField(
            model_name='client',
            name='medication_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da medicação'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pain_sensitivity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Sensibilidade à dor'),
        ),
        migrations.AlterField(
            model_name='client',
            name='perfusion_left',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Perfusão pé esquerdo'),
        ),
        migrations.AlterField(
            model_name='client',
            name='perfusion_left_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outra perfusão esquerda'),
        ),
        migrations.AlterField(
            model_name='client',
            name='perfusion_right',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Perfusão pé direito'),
        ),
        migrations.AlterField(
            model_name='client',
            name='perfusion_right_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outra perfusão direita'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plantar_view_left',
            field=models.TextField(blank=True, null=True, verbose_name='Vista plantar esquerda'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plantar_view_left_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outra vista plantar esquerda'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plantar_view_right',
            field=models.TextField(blank=True, null=True, verbose_name='Vista plantar direita'),
        ),
        migrations.AlterField(
            model_name='client',
            name='plantar_view_right_other',
            field=models.TextField(blank=True, null=True, verbose_name='Outra vista plantar direita'),
        ),
        migrations.AlterField(
            model_name='client',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='client',
            name='pregnancy_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da gravidez'),
        ),
        migrations.AlterField(
            model_name='client',
            name='professional',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clients', to=settings.AUTH_USER_MODEL, verbose_name='Profissional'),
        ),
        migrations.AlterField(
            model_name='client',
            name='professional_procedures',
            field=models.TextField(blank=True, null=True, verbose_name='Procedimentos realizados'),
        ),
        migrations.AlterField(
            model_name='client',
            name='sock_used',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Meia usada'),
        ),
        migrations.AlterField(
            model_name='client',
            name='state',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='client',
            name='surgery_details',
            field=models.TextField(blank=True, null=True, verbose_name='Detalhes da cirurgia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='takes_medication',
            field=models.BooleanField(blank=True, null=True, verbose_name='Toma medicação'),
        ),
    ]
