# Generated by Django 5.2.4 on 2025-07-11 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0008_alter_client_address_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='can_manage_professionals',
            field=models.BooleanField(default=False, verbose_name='Pode gerenciar profissionais'),
        ),
    ]
