# Generated by Django 5.2.4 on 2025-07-17 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0009_professional_can_manage_professionals'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professional',
            name='register_number',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True, verbose_name='Registro Profissional'),
        ),
    ]
