# Generated by Django 5.2.4 on 2025-07-28 22:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0011_client_cpf'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='footwear_other',
        ),
    ]
