# Generated by Django 5.2.4 on 2025-07-31 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0012_remove_client_footwear_other'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='bodybuilding_activity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Atividade de musculação'),
        ),
        migrations.AddField(
            model_name='client',
            name='sport_activity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Atividade esportiva'),
        ),
    ]
