# Generated by Django 5.2.4 on 2025-07-31 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_client_bodybuilding_activity_client_sport_activity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='clinical_history_other',
        ),
        migrations.RemoveField(
            model_name='client',
            name='medication_details',
        ),
        migrations.RemoveField(
            model_name='client',
            name='perfusion_right_other',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plantar_view_left_other',
        ),
        migrations.RemoveField(
            model_name='client',
            name='plantar_view_right_other',
        ),
        migrations.RemoveField(
            model_name='client',
            name='pregnancy_details',
        ),
        migrations.RemoveField(
            model_name='client',
            name='professional_procedures',
        ),
        migrations.RemoveField(
            model_name='client',
            name='surgery_details',
        ),
        migrations.AddField(
            model_name='client',
            name='other_procedures',
            field=models.TextField(blank=True, null=True, verbose_name='Outros procedimentos'),
        ),
    ]
