# Generated by Django 5.2.4 on 2025-07-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0014_remove_client_clinical_history_other_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='bodybuilding_activity',
        ),
        migrations.AddField(
            model_name='client',
            name='academic_activity',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Atividade acadêmica'),
        ),
    ]
