# Generated by Django 5.2.4 on 2025-08-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0015_remove_client_bodybuilding_activity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='perfusion_left',
        ),
        migrations.RemoveField(
            model_name='client',
            name='perfusion_left_other',
        ),
        migrations.RemoveField(
            model_name='client',
            name='perfusion_right',
        ),
        migrations.AlterField(
            model_name='client',
            name='had_surgery',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Já fez cirurgia'),
        ),
        migrations.AlterField(
            model_name='client',
            name='takes_medication',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Toma medicação'),
        ),
    ]
