# Generated by Django 5.2.4 on 2025-08-05 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0016_remove_client_perfusion_left_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='nail_changes_left',
            field=models.TextField(blank=True, null=True, verbose_name='Alterações nas unhas pé esquerdo'),
        ),
        migrations.AddField(
            model_name='client',
            name='nail_changes_right',
            field=models.TextField(blank=True, null=True, verbose_name='Alterações nas unhas pé direito'),
        ),
    ]
