# Generated by Django 5.2.4 on 2025-08-05 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0017_client_nail_changes_left_client_nail_changes_right'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='deformities_left',
            field=models.TextField(blank=True, null=True, verbose_name='Deformidades pé esquerdo'),
        ),
        migrations.AddField(
            model_name='client',
            name='deformities_right',
            field=models.TextField(blank=True, null=True, verbose_name='Deformidades pé direito'),
        ),
        migrations.AddField(
            model_name='client',
            name='sensitivity_test',
            field=models.TextField(blank=True, null=True, verbose_name='Teste de sensibilidade'),
        ),
    ]
