# Generated by GitHub Copilot on 2025-08-25
from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('register', '0022_rename_address_number_to_neighborhood'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='neighborhood',
            field=models.CharField(max_length=100, null=True, blank=True, verbose_name='Bairro'),
        ),
    ]
