# Generated by Django 5.2.4 on 2025-08-26 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0024_alter_medical_fields_length'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='phone',
            field=models.CharField(max_length=20, null=True, unique=True, verbose_name='Telefone'),
        ),
    ]
