# Generated by Django 5.2.4 on 2025-09-02 20:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0029_devicesession'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfessionalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start_hour', models.PositiveSmallIntegerField(default=8)),
                ('work_end_hour', models.PositiveSmallIntegerField(default=18)),
                ('slot_minutes', models.PositiveSmallIntegerField(default=30)),
                ('confirm_message_enabled', models.BooleanField(default=False)),
                ('confirm_message_template', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('professional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Configuração do Profissional',
                'verbose_name_plural': 'Configurações de Profissionais',
            },
        ),
    ]
