# Generated by Django 5.2.4 on 2025-09-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0031_professional_soft_delete'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='client',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento'),
        ),
    ]
