# Generated by ChatGPT on 2025-09-27
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0032_client_address_number_client_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='client_photos/', verbose_name='Foto'),
        ),
    ]
