# Generated by Django 5.2.4 on 2026-04-03 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0034_professionalsettings_pix_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='totp_secret',
            field=models.CharField(blank=True, help_text='Base32 secret for TOTP (Google Authenticator). Empty = TOTP not configured.', max_length=64, verbose_name='TOTP Secret'),
        ),
    ]
