# Generated by Django 5.2.4 on 2026-04-03 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0036_webauthn_credential'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccessCode',
        ),
    ]
