# Generated by Django 5.2.4 on 2026-04-08 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0039_pushsubscription_reminders'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='display_name',
            field=models.CharField(blank=True, help_text="Como os clientes a conhecem: ex. 'Podóloga Regiane', 'Dra. Juliana' ou 'Clínica Árcaro'. Se vazio, usa o primeiro nome.", max_length=100, verbose_name='Nome de exibição'),
        ),
    ]
