# Generated by Django 5.2.4 on 2026-04-22 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0043_delete_pushsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='professional',
            name='ui_theme',
            field=models.CharField(choices=[('blue', 'Azul'), ('green', 'Verde'), ('pink', 'Rosa'), ('black', 'Escuro')], default='blue', max_length=10, verbose_name='Tema da interface'),
        ),
        migrations.AlterField(
            model_name='professionalsettings',
            name='reminder_minutes_before',
            field=models.PositiveSmallIntegerField(default=90, help_text='Quantos minutos antes do compromisso enviar o lembrete Telegram.'),
        ),
    ]
