# Generated by Django 5.2.4 on 2026-04-04 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='document_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Número do documento'),
        ),
        migrations.AddField(
            model_name='client',
            name='document_type',
            field=models.CharField(blank=True, choices=[('cpf', 'CPF'), ('cnpj', 'CNPJ')], max_length=4, null=True, verbose_name='Tipo de documento'),
        ),
        migrations.AddField(
            model_name='client',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('solteiro', 'Solteiro(a)'), ('casado', 'Casado(a)'), ('divorciado', 'Divorciado(a)'), ('viuvo', 'Viúvo(a)'), ('uniao_estavel', 'União estável')], max_length=20, null=True, verbose_name='Estado civil'),
        ),
        migrations.AddField(
            model_name='client',
            name='nationality',
            field=models.CharField(blank=True, max_length=60, null=True, verbose_name='Nacionalidade'),
        ),
        migrations.AddField(
            model_name='client',
            name='sex',
            field=models.CharField(blank=True, choices=[('masculino', 'Masculino'), ('feminino', 'Feminino'), ('outro', 'Outro'), ('nao_informado', 'Prefiro não informar')], max_length=20, null=True, verbose_name='Sexo'),
        ),
    ]
