# Generated by Django 5.2.4 on 2026-04-04 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_add_client_personal_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='rg',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='RG'),
        ),
    ]
