# Generated by Django 5.2.4 on 2026-04-08 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_add_rg_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='address_complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Complemento'),
        ),
    ]
