# Generated by Django 5.2.4 on 2026-05-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_address_complement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='photo',
        ),
    ]
