# Generated by Django 5.2.4 on 2026-04-04 17:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0003_add_rg_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnamnesisField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sector', models.CharField(help_text='Agrupa visualmente os campos — ex: "Histórico", "Pé Direito"', max_length=100, verbose_name='Setor')),
                ('sector_order', models.PositiveSmallIntegerField(default=0, help_text='Ordem de exibição do setor na tela', verbose_name='Ordem do setor')),
                ('label', models.CharField(max_length=200, verbose_name='Pergunta')),
                ('field_type', models.CharField(choices=[('radio', 'Radio buttons'), ('text', 'Texto livre'), ('textarea', 'Texto longo')], default='radio', max_length=10, verbose_name='Tipo')),
                ('options', models.JSONField(blank=True, help_text='Lista de strings para radio buttons. Null para text/textarea.', null=True, verbose_name='Opções')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Ordem dentro do setor')),
                ('is_active', models.BooleanField(default=True, help_text='Desativar em vez de apagar preserva respostas históricas.', verbose_name='Ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis_fields', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Campo de anamnese',
                'verbose_name_plural': 'Campos de anamnese',
                'ordering': ['sector_order', 'order'],
            },
        ),
        migrations.CreateModel(
            name='AnamnesisResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_label_snap', models.CharField(help_text='Cópia do label no momento da resposta.', max_length=200, verbose_name='Pergunta (snapshot)')),
                ('value', models.TextField(blank=True, default='', verbose_name='Resposta')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamnesis_responses', to='clients.client', verbose_name='Cliente')),
                ('field', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='responses', to='anamnesis.anamnesisfield', verbose_name='Campo')),
            ],
            options={
                'verbose_name': 'Resposta de anamnese',
                'verbose_name_plural': 'Respostas de anamnese',
                'unique_together': {('client', 'field')},
            },
        ),
        migrations.CreateModel(
            name='AnamnesisPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='anamnesis_photos/', verbose_name='Foto')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Legenda')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='anamnesis.anamnesisresponse', verbose_name='Resposta')),
            ],
            options={
                'verbose_name': 'Foto de anamnese',
                'verbose_name_plural': 'Fotos de anamnese',
            },
        ),
    ]
