# Generated by Django 5.2.4 on 2026-04-22 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0002_conditional_field_support'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anamnesisfield',
            name='code',
            field=models.SlugField(blank=True, help_text='Identificador estável do campo para seeds, migrações e lógica de dependência.', max_length=120, verbose_name='Código'),
        ),
    ]
