# Generated by Django 5.2.4 on 2026-05-13 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anamnesis', '0003_alter_anamnesisfield_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AnamnesisPhoto',
        ),
    ]
