# Generated by Django 5.2.4 on 2026-04-27 13:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0004_client_address_complement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DentalArcade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_treatment_id', models.BigIntegerField(blank=True, help_text='ID_PT_HEADER da base legada (quando aplicavel).', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluido')], default='pending', max_length=20)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_arcades', to='clients.client', verbose_name='Cliente')),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dental_arcades', to=settings.AUTH_USER_MODEL, verbose_name='Profissional')),
            ],
            options={
                'verbose_name': 'Arcada dentaria',
                'verbose_name_plural': 'Arcadas dentarias',
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Tooth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(help_text='Posicao sequencial no mapa da arcada (1-32).')),
                ('international_number', models.PositiveSmallIntegerField(help_text='Numero internacional odontologico (11-48).')),
                ('external_arcade_row_id', models.BigIntegerField(blank=True, null=True)),
                ('observations', models.TextField(blank=True, default='')),
                ('anomalies_bitmap', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arcade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teeth', to='odonto.dentalarcade', verbose_name='Arcada')),
            ],
            options={
                'verbose_name': 'Dente',
                'verbose_name_plural': 'Dentes',
                'ordering': ['sequence'],
            },
        ),
        migrations.CreateModel(
            name='Surface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('O', 'Oclusal'), ('PO', 'Palatina/Oclusal'), ('MO', 'Mesial/Oclusal'), ('VO', 'Vestibular/Oclusal'), ('LDI', 'Lingual/Distal/Incisal')], max_length=10)),
                ('label', models.CharField(blank=True, default='', max_length=40)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tooth', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='surfaces', to='odonto.tooth', verbose_name='Dente')),
            ],
            options={
                'verbose_name': 'Face',
                'verbose_name_plural': 'Faces',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_item_id', models.BigIntegerField(blank=True, help_text='ID_PT_ITEM da base legada (quando aplicavel).', null=True)),
                ('code', models.CharField(blank=True, default='', max_length=40)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('completed', 'Concluido'), ('canceled', 'Cancelado')], default='pending', max_length=20)),
                ('region_raw', models.CharField(blank=True, default='', help_text='Valor original importado de TX_REGIAO.', max_length=30)),
                ('faces_raw', models.CharField(blank=True, default='', help_text='Valor original importado de TX_FACES.', max_length=30)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('completed_at', models.DateField(blank=True, null=True)),
                ('patient_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('paid_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('duration_minutes', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('arcade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procedures', to='odonto.dentalarcade', verbose_name='Arcada')),
                ('surface', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='odonto.surface', verbose_name='Face')),
                ('tooth', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='procedures', to='odonto.tooth', verbose_name='Dente')),
            ],
            options={
                'verbose_name': 'Procedimento odontologico',
                'verbose_name_plural': 'Procedimentos odontologicos',
                'ordering': ['id'],
            },
        ),
        migrations.AddIndex(
            model_name='dentalarcade',
            index=models.Index(fields=['professional', 'client'], name='odonto_dent_profess_76d3d6_idx'),
        ),
        migrations.AddIndex(
            model_name='dentalarcade',
            index=models.Index(fields=['professional', 'status'], name='odonto_dent_profess_29296c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='dentalarcade',
            unique_together={('professional', 'external_treatment_id')},
        ),
        migrations.AddIndex(
            model_name='tooth',
            index=models.Index(fields=['arcade', 'sequence'], name='odonto_toot_arcade__c5b1f8_idx'),
        ),
        migrations.AddIndex(
            model_name='tooth',
            index=models.Index(fields=['arcade', 'international_number'], name='odonto_toot_arcade__a5c703_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='tooth',
            unique_together={('arcade', 'international_number'), ('arcade', 'sequence')},
        ),
        migrations.AddIndex(
            model_name='surface',
            index=models.Index(fields=['tooth', 'code'], name='odonto_surf_tooth_i_f5eab9_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='surface',
            unique_together={('tooth', 'code')},
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['arcade', 'status'], name='odonto_proc_arcade__2bbeaa_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['arcade', 'tooth'], name='odonto_proc_arcade__38f334_idx'),
        ),
        migrations.AddIndex(
            model_name='procedure',
            index=models.Index(fields=['external_item_id'], name='odonto_proc_externa_7c14c0_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='procedure',
            unique_together={('arcade', 'external_item_id')},
        ),
    ]
