# Generated by Django 5.2.4 on 2026-05-02 22:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('odonto', '0006_seed_catalog_from_procedures'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='procedure',
            name='odonto_proc_arcade_is_produc_idx',
        ),
        migrations.RenameIndex(
            model_name='procedurenamesuggestion',
            new_name='odonto_proc_profess_350d4e_idx',
            old_name='odonto_proc_profess_5f8dd0_idx',
        ),
        migrations.RenameIndex(
            model_name='productcatalogitem',
            new_name='odonto_prod_profess_c2cf5f_idx',
            old_name='odonto_prod_profess_7e05e7_idx',
        ),
    ]
